# Generated by Django 5.0.6 on 2024-06-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='full_name',
        ),
    ]
