# Generated by Django 5.0.6 on 2024-06-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_billingaddress_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
