# Generated by Django 5.0.6 on 2024-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_billingaddress_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
    ]
